part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const DAFTAR_MATA_PELAJARAN = _Paths.DAFTAR_MATA_PELAJARAN;
  static const INFO_SEKOLAH = _Paths.INFO_SEKOLAH;
  static const TAMPILKAN_INFO_SEKOLAH = _Paths.TAMPILKAN_INFO_SEKOLAH;
  static const ACCOUNT_SWITCHER = _Paths.ACCOUNT_SWITCHER;
  static const DAFTAR_SPP = _Paths.DAFTAR_SPP;
  static const DAFTAR_PEMBAYARAN_KOMITE = _Paths.DAFTAR_PEMBAYARAN_KOMITE;
  static const JADWAL_AGIS = _Paths.JADWAL_AGIS;
  static const INPUT_JADWAL_AGIS = _Paths.INPUT_JADWAL_AGIS;
  static const INPUT_DANA_KOMITE = _Paths.INPUT_DANA_KOMITE;
  static const DAFTAR_NILAI_MATAPELAJARAN = _Paths.DAFTAR_NILAI_MATAPELAJARAN;
  static const INFO_SEKOLAH_DETAIL = _Paths.INFO_SEKOLAH_DETAIL;
  static const ROOT = _Paths.ROOT;
  static const SPLASH = _Paths.SPLASH;
  static const LENGKAPI_PROFIL = _Paths.LENGKAPI_PROFIL;
  static const SEMUA_NOTIFIKASI = _Paths.SEMUA_NOTIFIKASI;
  static const DETAIL_MAPEL_SISWA = _Paths.DETAIL_MAPEL_SISWA;
  static const HALAQAH_RIWAYAT_SISWA = _Paths.HALAQAH_RIWAYAT_SISWA;
  static const EKSKUL_SISWA = _Paths.EKSKUL_SISWA;
  static const KALENDER_AKADEMIK = _Paths.KALENDER_AKADEMIK;
  static const INFO_SEKOLAH_LIST = _Paths.INFO_SEKOLAH_LIST;
  static const JADWAL_SISWA = _Paths.JADWAL_SISWA;
  static const MARKETPLACE = _Paths.MARKETPLACE;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const DETAIL_KEUANGAN_SISWA = _Paths.DETAIL_KEUANGAN_SISWA;
  static const PEMBELIAN_BUKU = _Paths.PEMBELIAN_BUKU;
  static const MANAJEMEN_IURAN = _Paths.MANAJEMEN_IURAN;
  static const MANAJEMEN_AGIS = _Paths.MANAJEMEN_AGIS;
  static const MANAJEMEN_KOMITE_SEKOLAH = _Paths.MANAJEMEN_KOMITE_SEKOLAH;
  static const KAS_KOMITE = _Paths.KAS_KOMITE;
  static const LAPORAN_KOMITE = _Paths.LAPORAN_KOMITE;
  static const CATATAN_BK = _Paths.CATATAN_BK;
  static const CATATAN_BK_LIST = _Paths.CATATAN_BK_LIST;
  static const CATATAN_BK_DETAIL = _Paths.CATATAN_BK_DETAIL;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const NEW_PASSWORD = '/new-password';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const DAFTAR_MATA_PELAJARAN = '/daftar-mata-pelajaran';
  static const INFO_SEKOLAH = '/info-sekolah';
  static const TAMPILKAN_INFO_SEKOLAH = '/tampilkan-info-sekolah';
  static const ACCOUNT_SWITCHER = '/account-switcher';
  static const DAFTAR_SPP = '/daftar-spp';
  static const DAFTAR_PEMBAYARAN_KOMITE = '/daftar-pembayaran-komite';
  static const JADWAL_AGIS = '/jadwal-agis';
  static const INPUT_JADWAL_AGIS = '/input-jadwal-agis';
  static const INPUT_DANA_KOMITE = '/input-dana-komite';
  static const DAFTAR_NILAI_MATAPELAJARAN = '/daftar-nilai-matapelajaran';
  static const INFO_SEKOLAH_DETAIL = '/info-sekolah-detail';
  static const ROOT = '/root';
  static const SPLASH = '/splash';
  static const LENGKAPI_PROFIL = '/lengkapi-profil';
  static const SEMUA_NOTIFIKASI = '/semua-notifikasi';
  static const DETAIL_MAPEL_SISWA = '/detail-mapel-siswa';
  static const HALAQAH_RIWAYAT_SISWA = '/halaqah-riwayat-siswa';
  static const EKSKUL_SISWA = '/ekskul-siswa';
  static const KALENDER_AKADEMIK = '/kalender-akademik';
  static const INFO_SEKOLAH_LIST = '/info-sekolah-list';
  static const JADWAL_SISWA = '/jadwal-siswa';
  static const MARKETPLACE = '/marketplace';
  static const ONBOARDING = '/onboarding';
  static const DETAIL_KEUANGAN_SISWA = '/detail-keuangan-siswa';
  static const PEMBELIAN_BUKU = '/pembelian-buku';
  static const MANAJEMEN_IURAN = '/manajemen-iuran';
  static const MANAJEMEN_AGIS = '/manajemen-agis';
  static const MANAJEMEN_KOMITE_SEKOLAH = '/manajemen-komite-sekolah';
  static const KAS_KOMITE = '/kas-komite';
  static const LAPORAN_KOMITE = '/laporan-komite';
  static const CATATAN_BK = '/catatan-bk';
  static const CATATAN_BK_LIST = '/catatan-bk-list';
  static const CATATAN_BK_DETAIL = '/catatan-bk-detail';
}
